chore: add eslint
netlify/netlify-plugin-nextjs pull request #213
Opened 2021-04-11 08:18 UTC by lindsaylevine

Fixes https://github.com/netlify/netlify-plugin-nextjs/issues/210

had to push --no-verify because it was hanging?? not sure why, checked/compared to `cli` to see if i was missing a dep or something 🤔

2021-04-11 08:19 UTC, lindsaylevine commented
![Screen Shot 2021-04-11 at 4 17 26 AM](https://user-images.githubusercontent.com/57350178/114297181-26f34a00-9a7d-11eb-8765-1714e072c2f6.png)

2021-04-11 08:56 UTC, lindsaylevine commented
also not sure about the ci failures with `run-s` 🤡

2021-04-12 07:50 UTC, erezrokah requested changes
> had to push --no-verify because it was hanging?? not sure why, checked/compared to cli to see if i was missing a dep or something 🤔

I thought it was hanging too, but then it reported over 2000 errors, so maybe it's just slow?

2021-04-12 07:50 UTC, erezrokah commented on .github/workflows/test.yml
> +      - name: Linting
This should be after the `npm install` step to fix the `run-s` errors.
Also in CI actions it's better to use `npm ci` to have reproducible builds (also it's faster than `npm install`).

2021-04-26 08:11 UTC, erezrokah approved these changes

2021-04-26 15:31 UTC, ehmicky requested changes
:tada: 
Note: CI tests are failing.

2021-04-27 14:58 UTC, ehmicky commented on .eslintrc.js
> +    rules: {
Note: instead of using overrides, it it possible to put those `rules` directly under the top-level `rules` property.

2021-04-28 12:30 UTC, closed without merging